%% The following codes are baesd on "www.pnas.org/cgi/doi/10.1073/pnas.2002959117"
function model = setMediaConditions(model,bound)
exchangeReactions = {'ammonium exchange' ...
'sulphate exchange' ...
'biotin exchange' ...
'(R)-pantothenate exchange' ...
'folic acid exchange' ...
'myo-inositol exchange' ...
'nicotinate exchange' ...
'4-aminobenzoate exchange' ...
'pyridoxine exchange' ...
'H+ exchange' ...
'riboflavin exchange' ...
'thiamine(1+) exchange' ...
'sulphate exchange' ...
'potassium exchange' ...
'phosphate exchange' ...
'sulphate exchange' ...
'sodium exchange' ...
'L-alanine exchange' ...
'L-arginine exchange' ...
'L-asparagine exchange' ...
'L-aspartate exchange' ...
'L-cysteine exchange' ...
'L-glutamate exchange' ...
'L-glutamine exchange' ...
'L-glycine exchange' ...
'L-histidine exchange' ...
'L-isoleucine exchange' ...
'L-leucine exchange' ...
'L-lysine exchange' ...
'L-methionine exchange' ...
'L-phenylalanine exchange' ...
'L-proline exchange' ...
'L-serine exchange' ...
'L-threonine exchange' ...
'L-tryptophan exchange' ...
'L-tyrosine exchange' ...
'L-valine exchange' ...
'oxygen exchange' ...
'adenine exchange' ...
'uracil exchange'};
for i = 1 : numel(exchangeReactions)
     model.lb(model.rxns{find(ismember(model.rxnNames, exchangeReactions{i}),1)}) = bound;
     %disp(exchangeReactions{i})
end

end

